// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "translation": {
    "about": {
      "badge": "About Me",
      "content": "I'm a <1>Full Stack</1> developer passionate about transforming lines of code into real solutions. With solid experience in <2>web development<2>, my mission is to create architectures that are not only functional, but also scalable and elegant. My career path spans from complex enterprise applications to process automation, always with an obsessive focus on <3>performance<3> and user experience.",
      "founder": {
        "description": "Software house focused on technical excellence and innovation."
      },
      "stacks": {
        "backend": "Back-end",
        "database": "Database",
        "frontend": "Front-end",
        "tools": "Tools"
      },
      "title": "Hello, I'm Douglas Maia!"
    },
    "hero": {
      "badge": "Full Stack Developer",
      "description": "Transforming complex ideas into high-performance code. Experts in building scalable architectures and immersive interfaces.",
      "explore": "Explore my projects",
      "talk": "Let's talk",
      "terminal": {
        "return": "Incredible Solutions"
      },
      "title": "Creator of <1>Digital Solutions</1>"
    }
  }
}

export default Resources;
