// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "translation": {
    "hero": {
      "badge": "Full Stack Developer",
      "description": "Transforming complex ideas into high-performance code. Experts in building scalable architectures and immersive interfaces.",
      "explore": "Explore my projects",
      "talk": "Let's talk",
      "terminal": {
        "return": "Incredible Solutions"
      },
      "title": "Creator of Digital Solutions"
    }
  }
}

export default Resources;
